name = "Corvex Friends"
author = "bodathomas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3277fd85675ae8c70e2f885e01b5ed04b3bc2cb6c04eae25ee9b34e9bd499be2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
