name = "Corvex Friends"
author = "bodathomas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebc3826db381491c8ddd54f2864051737cf7a9fb155ebdaab494bfb709f5c836"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
