name = "Corvex Friends"
author = "bodathomas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20ac10b492ff6702739fb54e0e9b8668b0ef8eb7aee4ac7e1ad5489377c2073d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
